name: Build and Push Docker Image

on:
  push:
    branches-ignore:
      - "v*"
    tags:
      - "v*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      REPO: docker.hq-hydra.hibyte.ro/hibyte/horus
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Extract Docker Tag
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Install Dependencies
        run: npm install
      - name: Build Angular Project
        run: npm run build --progress=true

      - name: Login to Docker Hub
        run: docker login docker.hq-hydra.hibyte.ro -u ${{ secrets.HIBYTE_NEXUS_USER }} -p ${{ secrets.HIBYTE_NEXUS_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $REPO:${GITHUB_REF##*/} -t $REPO:${GITHUB_SHA::8} .

      #      - name: Tag Latest if necessary
      #        if: "false"
      #        run: docker tag $REPO:${GITHUB_REF##*/} $REPO:latest

      - name: Publish Docker image
        run: docker push $REPO -a
